### ISSUE TITLE
interpreter make failed by ocaml

### ISSUE THREAD

**Issue by zhenweijin** [WebAssembly/gc#356]
ocamlbuild version 0.14.2
ocaml version 4.14.0
opam version 2.1.4 

when run `make ` in the path of `gc/interpreter`,
error message

```shell
echo >_tags "true: bin_annot"
echo >>_tags "true: debug"
echo >>_tags "<{util,syntax,binary,text,valid,runtime,exec,script,host,main,tests}/*.cmx>: for-pack(Wasm)"
ocamlbuild -lexflags -ml -cflags '-w +a-4-27-42-44-45-70 -warn-error +a-3' -I util -I syntax -I binary -I text -I valid -I runtime -I exec -I script -I host -I main -I tests -libs bigarray -quiet main.native
+ /home/zhenwei/.opam/4.14.0/bin/ocamlopt.opt -c -w +a-4-27-42-44-45-70 -warn-error +a-3 -g -bin-annot -for-pack Wasm -I exec -I text -I runtime -I binary -I main -I syntax -I script -I util -I host -I tests -I valid -o exec/eval.cmx exec/eval.ml
File "exec/eval.ml", line 1:
Error: syntax/ast.cmi is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
Command exited with code 2.
make: *** [Makefile:71: main.native] Error 10
rm _tags

```

when ocaml version is 4.08.1, the same command 'make' throw the error:

```shell
cho >_tags "true: bin_annot"
echo >>_tags "true: debug"
echo >>_tags "<{util,syntax,binary,text,valid,runtime,exec,script,host,main,tests}/*.cmx>: for-pack(Wasm)"
ocamlbuild -lexflags -ml -cflags '-w +a-4-27-42-44-45-70 -warn-error +a-3' -I util -I syntax -I binary -I text -I valid -I runtime -I exec -I script -I host -I main -I tests -libs bigarray -quiet main.native
+ ocamlopt.opt -c -w +a-4-27-42-44-45-70 -warn-error +a-3 -g -bin-annot -for-pack Wasm -I exec -I text -I runtime -I binary -I main -I syntax -I script -I util -I host -I tests -I valid -o exec/eval.cmx exec/eval.ml
File "exec/eval.ml", line 675, characters 40-56:
675 |                 Num (I32 (I32.of_int_u (String.get_uint8 bs j)))
                                              ^^^^^^^^^^^^^^^^
Error: Unbound value String.get_uint8
Command exited with code 2.
make: *** [Makefile:71: main.native] Error 10
rm _tags
```

**Comment by rossberg** [comment]
Yes, it won't build with 4.08 anymore.

The former error happens when you still have an old build of the interpreter lying around. Try running `make clean` first.

**Comment by zhenweijin** [comment]
get it, thanks~
